### ISSUE TITLE
Name Refactoring on ParsersRule throws NPE

### ISSUE THREAD

**Issue by Spieki** [eclipse/xtext-core#111]
To reproduce the error:
   -Open a Xtext Grammar
   -Select ParserRule
   -Choose Rename Element from Context menu

`java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:398)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:481)
	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:242)
	at org.eclipse.ui.internal.progress.ProgressManager$3.run(ProgressManager.java:895)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.progress.ProgressManager.busyCursorWhile(ProgressManager.java:930)
	at org.eclipse.ui.internal.progress.ProgressManager.busyCursorWhile(ProgressManager.java:905)
	at org.eclipse.ui.internal.progress.ProgressManager.run(ProgressManager.java:1078)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.totalSync(SyncUtil.java:59)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.totalSync(SyncUtil.java:52)
	at org.eclipse.xtext.ui.refactoring.ui.DefaultRenameElementHandler.execute(DefaultRenameElementHandler.java:70)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:54)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.waitForReconciler(SyncUtil.java:135)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.reconcileAllEditors(SyncUtil.java:102)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.doReconcileAndBuild(SyncUtil.java:75)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.access$0(SyncUtil.java:71)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil$1.run(SyncUtil.java:62)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Root exception:
java.lang.NullPointerException
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.waitForReconciler(SyncUtil.java:135)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.reconcileAllEditors(SyncUtil.java:102)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.doReconcileAndBuild(SyncUtil.java:75)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil.access$0(SyncUtil.java:71)
	at org.eclipse.xtext.ui.refactoring.ui.SyncUtil$1.run(SyncUtil.java:62)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)`

**Comment by kthoms** [comment]
![screenshot 20](https://cloud.githubusercontent.com/assets/265597/18669991/df080c94-7f3d-11e6-8a4b-a695a2047197.png)

Could not reproduce the issue. Rename refactoring dialog pops up.

**Comment by Spieki** [comment]
After a Restart of eclipse everything works fine for me too. But after a time i get the same Problem again and then it es in every Project, even in new ones. But for now i don´t get action that made this Problem start. If I find the way of getting this Problem, I will reopen the Issue.
