### ISSUE TITLE
Formatting2 IllegalArgumentException when calling NodeRegion.toString()

### ISSUE THREAD

**Issue by torstenkraemer** [eclipse/xtext-core#12]
Encountered while Debugging a sufficiently deep structure: 

```
java.lang.IllegalArgumentException: invalid count: -1
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.google.common.base.Strings.repeat(Strings.java:157)
    at org.eclipse.xtext.formatting2.debug.TextRegionAccessToString.indent(TextRegionAccessToString.java:220)
    at org.eclipse.xtext.formatting2.debug.TextRegionAccessToString.toString(TextRegionAccessToString.java:205)
    at org.eclipse.xtext.formatting2.regionaccess.internal.NodeRegion.toString(NodeRegion.java:53)
```

**Comment by holgerschill** [comment]
Hard to reproduce. Could you provide an example?
