### ISSUE TITLE
textDocument/documentSymbol failed Concurrent modification on hovering on code.

### ISSUE THREAD

**Issue by Rajsmit** [eclipse/xtext-core#1319]
Observing a exception while doing hover (intermittent).

Once build completes results:
SEVERE: Internal error: java.util.ConcurrentModificationException
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758)
at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712)
at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692)
at org.eclipse.emf.common.util.AbstractTreeIterator.next(AbstractTreeIterator.java:133)
at org.eclipse.xtext.ide.server.symbol.HierarchicalDocumentSymbolService.getSymbols(HierarchicalDocumentSymbolService.java:96)
at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getSymbols(DocumentSymbolService.java:186)
at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getSymbols(DocumentSymbolService.java:177)
at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$null$39(LanguageServerImpl.java:672)
at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:334)
at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$documentSymbol$40(LanguageServerImpl.java:674)
at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
... 4 more

[Trace - 12:51:33 PM] Received response 'textDocument/documentSymbol - (24)' in 606ms. Request failed: Internal error. (-32603).
[Error - 12:51:33 PM] Request textDocument/documentSymbol failed.
Message: Internal error.
Code: -32603
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758)
at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712)
at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692)
at org.eclipse.emf.common.util.AbstractTreeIterator.next(AbstractTreeIterator.java:133)
at org.eclipse.xtext.ide.server.symbol.HierarchicalDocumentSymbolService.getSymbols(HierarchicalDocumentSymbolService.java:96)
at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getSymbols(DocumentSymbolService.java:186)
at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getSymbols(DocumentSymbolService.java:177)
at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$null$39(LanguageServerImpl.java:672)
at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:334)
at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$documentSymbol$40(LanguageServerImpl.java:674)
at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
... 4 more

**Comment by tivervac** [comment]
Possibly related to https://github.com/eclipse/xtext/issues/2526

**Comment by szarnekow** [comment]
Likely caused by some lazily created objects. Please re-open in https://github.com/eclipse/xtext if you see this again.
