### ISSUE TITLE
Grammar fails to generate with Xtext 2.24 due to bug in new 

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1666]
```
Model:
	greetings+=Greeting*;
	
Greeting:
	'Hello' name=ID '!';

@Override 
terminal ML_COMMENT: '/*'(!'*')->'*/';
```

```
55  [main] ERROR clipse.xtext.util.ExceptionAcceptor  - Conflicting Regions.
{{{}}}: space='' at offset=39 length=0
[[[]]]: space=' ';newLine=0-0-1;autowrap at offset=39 length=0
------------------------------- document snippet -------------------------------
@Override 
terminalML_COMMENT: '/*'!'*'{{{}}}[[[]]]->'*/';
--------------------------------------------------------------------------------
org.eclipse.xtext.formatting2.internal.ConflictingRegionsException: Conflicting Regions.
{{{}}}: space='' at offset=39 length=0
[[[]]]: space=' ';newLine=0-0-1;autowrap at offset=39 length=0
------------------------------- document snippet -------------------------------
@Override 
terminalML_COMMENT: '/*'!'*'{{{}}}[[[]]]->'*/';
--------------------------------------------------------------------------------
	at org.eclipse.xtext.formatting2.internal.TextSegmentSet.handleConflict(TextSegmentSet.java:79)
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.replaceExistingEntry(ArrayListTextSegmentSet.java:178)
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:51)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:78)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.set(FormattableDocument.java:309)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.surround(FormattableDocument.java:332)
	at org.eclipse.xtext.xtext.XtextFormatterJava.format(XtextFormatterJava.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:303)
	at org.eclipse.xtext.formatting2.AbstractJavaFormatter.format(AbstractJavaFormatter.java:117)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:189)
	at org.eclipse.xtext.xtext.XtextFormatterJava.formatGroupElements(XtextFormatterJava.java:217)
	at org.eclipse.xtext.xtext.XtextFormatterJava.format(XtextFormatterJava.java:112)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:303)
	at org.eclipse.xtext.formatting2.AbstractJavaFormatter.format(AbstractJavaFormatter.java:117)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:189)
	at org.eclipse.xtext.xtext.XtextFormatterJava.formatRule(XtextFormatterJava.java:234)
	at org.eclipse.xtext.xtext.XtextFormatterJava.format(XtextFormatterJava.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:303)
	at org.eclipse.xtext.formatting2.AbstractJavaFormatter.format(AbstractJavaFormatter.java:117)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:189)
	at org.eclipse.xtext.xtext.XtextFormatterJava.format(XtextFormatterJava.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:303)
	at org.eclipse.xtext.formatting2.AbstractJavaFormatter.format(AbstractJavaFormatter.java:117)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:189)
	at org.eclipse.xtext.formatting2.AbstractFormatter2._format(AbstractFormatter2.java:209)
	at org.eclipse.xtext.formatting2.AbstractJavaFormatter.format(AbstractJavaFormatter.java:110)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.handleTraceMissing(AbstractFormatter2.java:296)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.format(AbstractFormatter2.java:279)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:155)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:184)
	at org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessExtensions.grammarFragmentToString(GrammarAccessExtensions.java:614)
	at org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessExtensions.grammarFragmentToString(GrammarAccessExtensions.java:604)
	at org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessFragment2$13.appendTo(GrammarAccessFragment2.java:916)
	at org.eclipse.xtend2.lib.StringConcatenation.append(StringConcatenation.java:309)
	at org.eclipse.xtend2.lib.StringConcatenation.append(StringConcatenation.java:227)
	at org.eclipse.xtend2.lib.StringConcatenation$SimpleTarget.append(StringConcatenation.java:691)
	at org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessFragment2$2.appendTo(GrammarAccessFragment2.java:493)
	at org.eclipse.xtend2.lib.StringConcatenation.append(StringConcatenation.java:177)
	at org.eclipse.xtext.xtext.generator.model.JavaFileAccess.setContent(JavaFileAccess.java:170)
	at org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessFragment2.doGenerateGrammarAccess(GrammarAccessFragment2.java:501)
	at org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessFragment2.generate(GrammarAccessFragment2.java:110)
	at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:43)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:231)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:133)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:35)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:213)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:38)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:21)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:103)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:79)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:37)
	Suppressed: org.eclipse.xtext.formatting2.internal.RegionTrace: space=''
		at org.eclipse.xtext.formatting2.internal.TextSegmentSet.trace(TextSegmentSet.java:117)
		at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:45)
		... 65 more
	Suppressed: org.eclipse.xtext.formatting2.internal.RegionTrace: space=' ';newLine=0-0-1;autowrap
		at org.eclipse.xtext.formatting2.internal.TextSegmentSet.trace(TextSegmentSet.java:117)
		at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.replaceExistingEntry(ArrayListTextSegmentSet.java:169)
		at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:51)
		at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:78)
		at org.eclipse.xtext.formatting2.internal.FormattableDocument.set(FormattableDocument.java:322)
		at org.eclipse.xtext.formatting2.internal.FormattableDocument.prepend(FormattableDocument.java:285)
		at org.eclipse.xtext.xtext.XtextFormatterJava.formatGroupElements(XtextFormatterJava.java:214)
		... 53 more
Caused by: org.eclipse.xtext.formatting2.ConflictingFormattingException: Conflicting values for 'space': ' ' and ''.
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormatting.merge(HiddenRegionFormatting.java:103)
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormatting.mergeValuesFrom(HiddenRegionFormatting.java:111)
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormattingMerger.merge(HiddenRegionFormattingMerger.java:33)
	at org.eclipse.xtext.formatting2.internal.HiddenRegionFormattingMerger.merge(HiddenRegionFormattingMerger.java:20)
	at org.eclipse.xtext.formatting2.internal.TextReplacerMerger.mergeHiddenRegionReplacers(TextReplacerMerger.java:74)
	at org.eclipse.xtext.formatting2.internal.TextReplacerMerger.merge(TextReplacerMerger.java:37)
	at org.eclipse.xtext.formatting2.internal.TextReplacerMerger.merge(TextReplacerMerger.java:24)
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.replaceExistingEntry(ArrayListTextSegmentSet.java:167)
	... 66 more
```

**Comment by cdietrich** [comment]
Potential Workaround

```
package org.xtext.example.mydsl;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.nodemodel.util.NodeModelUtils;
import org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessExtensions;

public class GrammarAccessExtensionsCustom extends GrammarAccessExtensions {

	@Override
	public String grammarFragmentToString(EObject ele, String prefix) {
		String s = NodeModelUtils.findActualNodeFor(ele).getText();
		s = prefix + s.trim().replaceAll("(\\r?\\n)", "$1" + prefix).replace("\\u", "\\\\u");
		return s;
	}

}

```

```
package org.xtext.example.mydsl;

import org.eclipse.xtext.xtext.generator.DefaultGeneratorModule;
import org.eclipse.xtext.xtext.generator.grammarAccess.GrammarAccessExtensions;

import com.google.inject.Binder;

public class MyDslGeneratorModule extends DefaultGeneratorModule {
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(GrammarAccessExtensions.class).to(GrammarAccessExtensionsCustom.class);
	}

}

```

```
module org.xtext.example.mydsl.GenerateMyDsl

import org.eclipse.xtext.xtext.generator.*
import org.eclipse.xtext.xtext.generator.model.project.*

var rootPath = ".."

Workflow {
	
	component = XtextGenerator {
		configuration = org.xtext.example.mydsl.MyDslGeneratorModule {
```

**Comment by cdietrich** [comment]
TODO: add testcase so that we dont fail in the future

**Comment by cdietrich** [comment]
test added to 2.25.
problem was already solved anyway
