### ISSUE TITLE
XtextDocument.readOnly() doesn't admit multiple readers

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/xtext-core#1731]
Methods in the vicinity of `XtextDocument.readOnly()` are documented with statements like "Gets a read-only copy of the State ...".

While the implementation doesn't seem to copy anything, it is possibly to create deadlocks by just requesting read-only access to 2 resources in the typical deadly embrace:
* Thread T1 held a lock on resource R1 and requested a lock on resource R2.
* Thread T2 held a lock on resource R2 and requested a lock on resource R1.

I'm not sure if allowing multiple readers has ever been intended?

Shouldn't at least `IReadAccess.tryReadOnly()` have a means to avoid deadlock?

(Originally asked [in the forum](https://www.eclipse.org/forums/index.php/m/1843569/#msg_1843569))

**Comment by szarnekow** [comment]
The API is unfortunately indeed as it suggests a property that cannot be guaranteed.
In EMF there is no such thing as a readonly operation. Every IUnitOfWork can potentially trigger proxy resolution or resource loading and would thereby be a modifying operation.
That's why the readOnly and modify are both using an exclusive lock.

A system that wants to use multiple threads with an Xtext based Eclipse IDE, has to apply some higher level concurrency controls.

The `try*` methods suggest that they try to lock, but in fact the meaning of try is different here: They guard against IUnitOfWork being called with a null-state. They only try to run the unit of work, if the state is present.

**Comment by stephan-herrmann** [comment]
Thanks, @szarnekow for clarification.

Looking at the different methods of `XtextDocument` and friends, it seems like `readOnly()` is most at risk of deadlock, whereas `priorityReadOnly()` and `modify()` at least try to **cancel (other) readers**.  Looking at the code, however, "all readers" only refers to the current validationJob, right? 

Since a validation job was one of the parties in our deadlock this would already help, unless validation already arrived at the attempt to lock the second resource, at which point it would not be cancelable.

Let me mention two more surprises from looking at our deadlock:

(1) One call to `tryReadOnly` originated from a call to `IResourceDescription.getReferenceDescriptions()`. I had hoped that working from "Descriptions" would avoid access to actual resources, but as in this case a `DocumentBasedDirtyResource` was involved, it apparently needs to access the resource. Just saying.

(2) I was even more surprised by the following part of a stack trace:
```
    "main":
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:512)
	- waiting to lock <0x000000071c95d680> (a org.eclipse.xtext.linking.lazy.LazyLinkingResource)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:53)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:71)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.lambda$0(XtextDocument.java:572)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker$$Lambda$951/0x000000080146f440.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	- locked <0x000000077a1e3f98> (a org.eclipse.swt.widgets.RunnableLock)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4928)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4449)
	at org.eclipse.ui.internal.dialogs.EventLoopProgressMonitor.runEventLoop(EventLoopProgressMonitor.java:127)
	at org.eclipse.ui.internal.dialogs.EventLoopProgressMonitor.setTaskName(EventLoopProgressMonitor.java:166)
	at org.eclipse.core.runtime.SubMonitor$RootInfo.setTaskName(SubMonitor.java:246)
	at org.eclipse.core.runtime.SubMonitor.beginTaskImpl(SubMonitor.java:637)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:479)
	at org.eclipse.xtext.ide.serializer.impl.ChangeSerializer.endRecordChanges(ChangeSerializer.java:191)
```
Here things get messed up, because the ChangeSerializer admits foreign work (via the monitor!!), which was triggered by some unknown thread via `notifyModelListenersOnUiThread`.  I say "messed up" because the same thread ("main") now requires to lock a (second) resource, without the original function of that thread (ChangeSerializer) having any control over this.

Perhaps, we need to avoid using an `EventLoopProgressMonitor` during serialization, but it wasn't our choice to begin with. It's the doing of `BatchModification.apply()` -> `WorkspaceModifyOperation.run()`.

=> Should I file a separate issue about this (i.e., ChangeSerializer launching an operation with EventLoopProgressMonitor)?

All this illustrates, that our own influence on the situation is slim :)

**Comment by stephan-herrmann** [comment]
Next I'm afraid that canceling other readers will not succeed against `XtextDocument.notifyModelListenersOnUiThread()`, because the `asyncExec()` will check for cancellation only inside `notifyModelListeners()`, i.e., after acquiring the lock. IMHO it must additionally check for cancellation before `tryReadOnly()`.
