### ISSUE TITLE
[LanguageServer] translateKind crashes with NPE if ContentAssistEntry.kind == null

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#19]
java.lang.NullPointerException
	at org.eclipse.xtext.ide.server.LanguageServerImpl.translateKind(LanguageServerImpl.java:466)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.toCompletionItem(LanguageServerImpl.java:458)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$null$39(LanguageServerImpl.java:433)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:365)
	at com.google.common.collect.Lists.newArrayList(Lists.java:162)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:555)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$40(LanguageServerImpl.java:436)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runRead$53(RequestManager.java:129)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by cdietrich** [comment]
i guess kind should be preinitialized with org.eclipse.xtext.ide.editor.contentassist.ContentAssistEntry.KIND_UNKOWN
or the translateKind should be nullsafe 
@spoenemann @svenefftinge

**Comment by svenefftinge** [comment]
I think this is no longer valid with the switch to enums

**Comment by cdietrich** [comment]
So the enums have a default value?

**Comment by cdietrich** [comment]
Hmm the npe will happen on our side of the Api.

**Comment by cdietrich** [comment]
still happens if you call

```
proposalCreator.createProposal("xxxxxx", c.prefix,c, null, null)
```

**Comment by svenefftinge** [comment]
Yes, it must not be null. I only added that to the underlying documentation not the doc of this method, though.

**Comment by cdietrich** [comment]
ok so we leave it with that?

**Comment by spoenemann** [comment]
I added an additional null check in `IdeContentProposalCreator` for convenience.
