### ISSUE TITLE
[LanguageServer] Formatting is no longer working. client never gets response

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#196]
Problem seems to be that the reflectivemessagevalidator walks up to guice

**Comment by cdietrich** [comment]
it seems to help to explicitely copy the lazy collection list to a new list

**Comment by cdietrich** [comment]
@spoenemann @svenefftinge what do you think? should this work with the lazy collections as well?

**Comment by svenefftinge** [comment]
I cannot see such an issue for our uses. Could you explain in more detail what happens in your case?

**Comment by cdietrich** [comment]
Formatter is no longer working. If i debug the Server I see issues produced by the reflective validator

**Comment by cdietrich** [comment]
@sven do you use formatter in your usecase?

**Comment by cdietrich** [comment]
```
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:49)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.validate(ReflectiveMessageValidator.java:60)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:34)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$2(RemoteEndpoint.java:201)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint$$Lambda$17/1658744451.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cdietrich** [comment]
on the object

```
objectStack.get(7)
	 (com.google.common.collect.Lists$TransformingRandomAccessList<F,T>) [TextEdit [
  range = Range [
    start = Position [
      line = 0
      character = 0
    ]
    end = Position [
      line = 0
      character = 0
    ]
  ]
  newText = "\n\n"
], TextEdit [
  range = Range [
    start = Position [
      line = 0
      character = 12
    ]
    end = Position [
      line = 1
      character = 0
    ]
  ]
  newText = "\n\n"
], TextEdit [
  range = Range [
    start = Position [
      line = 1
      character = 12
    ]
    end = Position [
      line = 1
      character = 13
    ]
  ]
  newText = "\n	"
], TextEdit [
  range = Range [
    start = Position [
      line = 1
      character = 24
    ]
    end = Position [
      line = 2
      character = 0
    ]
  ]
  newText = "\n\n"
], TextEdit [
  range = Range [
    start = Position [
      line = 2
      character = 14
    ]
    end = Position [
      line = 2
      character = 15
    ]
  ]
  newText = "\n	"
], TextEdit [
  range = Range [
    start = Position [
      line = 2
      character = 26
    ]
    end = Position [
      line = 3
      character = 0
    ]
  ]
  newText = "\n\n"
]]
	 (org.eclipse.lsp4j.jsonrpc.messages.ResponseMessage) {
  "id": "1",
  "result": [
    {
      "range": {
        "start": {
          "line": 0,
          "character": 0
        },
        "end": {
          "line": 0,
          "character": 0
        }
      },
      "newText": "\n\n"
    },
    {
      "range": {
        "start": {
          "line": 0,
          "character": 12
        },
        "end": {
          "line": 1,
          "character": 0
        }
      },
      "newText": "\n\n"
    },
    {
      "range": {
        "start": {
          "line": 1,
          "character": 12
        },
        "end": {
          "line": 1,
          "character": 13
        }
      },
      "newText": "\n\t"
    },
    {
      "range": {
        "start": {
          "line": 1,
          "character": 24
        },
        "end": {
          "line": 2,
          "character": 0
        }
      },
      "newText": "\n\n"
    },
    {
      "range": {
        "start": {
          "line": 2,
          "character": 14
        },
        "end": {
          "line": 2,
          "character": 15
        }
      },
      "newText": "\n\t"
    },
    {
      "range": {
        "start": {
          "line": 2,
          "character": 26
        },
        "end": {
          "line": 3,
          "character": 0
        }
      },
      "newText": "\n\n"
    }
  ],
  "jsonrpc": "2.0"
}
```

the validator walks up

FunctionDelegate -> org.eclipse.xtext.ide.server.formatting.FormattingService$$Lambda$86/1004592895@317e6189 -> org.eclipse.xtext.ide.server.formatting.FormattingService@2a8c757a -> FactoryProxy[key=Key[type=org.eclipse.xtext.formatting2.IFormatter2, annotation=[none]], provider=com.google.inject.internal.ConstructorBindingImpl$Factory@53fe788a]

....

**Comment by cdietrich** [comment]
if i replace the lazy guava list with a copy (Lists.newArrayList) as i do in my pullreq i dont get any issues

**Comment by svenefftinge** [comment]
Ok, got it. It should be fixed in LSP4J.

**Comment by svenefftinge** [comment]
it is fixed on lsp4j now
