### ISSUE TITLE
NPE following usage of  FoldingRangeService

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#1973]
ep 27, 2022 3:04:49 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.ide.editor.folding.DefaultFoldingRangeProvider.computeObjectFolding(DefaultFoldingRangeProvider.java:67)
	at org.eclipse.xtext.ide.editor.folding.DefaultFoldingRangeProvider.getFoldingRanges(DefaultFoldingRangeProvider.java:60)
	at org.eclipse.xtext.ide.server.folding.FoldingRangeService.createFoldingRanges(FoldingRangeService.java:37)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$foldingRange$50(LanguageServerImpl.java:1045)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:460)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.foldingRange(LanguageServerImpl.java:1044)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$foldingRange$49(LanguageServerImpl.java:1032)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	... 5 more

**Comment by rubenporras** [comment]
It looks to me than in org.eclipse.xtext.ide.server.folding.FoldingRangeService.createFoldingRanges(Document, XtextResource, CancelIndicator) both the document and the resource could be null, because that is a valid case for workspaceManager.doRead, as called in org.eclipse.xtext.ide.server.LanguageServerImpl.foldingRange(FoldingRangeRequestParams, CancelIndicator), so we should guard against it.

**Comment by cdietrich** [comment]
@rubenporras is this fixed?

**Comment by rubenporras** [comment]
yes
