### ISSUE TITLE
Error creating PDA for syntactic sequencer using Maven

### ISSUE THREAD

**Issue by S-wald** [eclipse/xtext-core#2028]
As discussed in https://www.eclipse.org/forums/index.php/t/1112014/ building a xtext DSL with three grammars in the hierarchy (MyDsl -with-> Base2 -with-> Base) leads to to an error during the workflow for the last grammar (MyDsl). @cdietrich suggested to ping @szarnekow. 

Sample project: [project.zip](https://github.com/eclipse/xtext-core/files/10069466/project.zip)

Error:
```
1137 ERROR SyntacticSequencerPDAProvider - Error creating PDA for syntactic sequencer for contexts: Basic2 returns Basic2: no type found for name=unresolved_rule
java.lang.RuntimeException: no type found for name=unresolved_rule
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.getType(SyntacticSequencerPDAProvider.java:703)
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.createAbsorberState(SyntacticSequencerPDAProvider.java:564)
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.createAbsorberState(SyntacticSequencerPDAProvider.java:569)
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.getSyntacticSequencerPDAs(SyntacticSequencerPDAProvider.java:631)
        at org.eclipse.xtext.serializer.analysis.SemanticSequencerNfaProvider.getSemanticSequencerNFAs(SemanticSequencerNfaProvider.java:240)
        at org.eclipse.xtext.serializer.analysis.GrammarConstraintProvider.getConstraints(GrammarConstraintProvider.java:624)
        at org.eclipse.xtext.xtext.generator.serializer.SemanticSequencerExtensions.getGrammarConstraints(SemanticSequencerExtensions.java:112)
        at org.eclipse.xtext.xtext.generator.serializer.SerializerFragment2.generateAbstractSemanticSequencer(SerializerFragment2.java:417)
        at org.eclipse.xtext.xtext.generator.serializer.SerializerFragment2.generate(SerializerFragment2.java:211)
        at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:43)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:228)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:133)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:35)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:213)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:38)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:21)
        at org.eclipse.emf.mwe2.launch.runtime.M
we2Runner.run(Mwe2Runner.java:103)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:829)
1142 ERROR SyntacticSequencerPDAProvider - Error creating PDA for syntactic sequencer for contexts: KEYWORDID2 returns null: no type found for unresolved_rule
java.lang.RuntimeException: no type found for unresolved_rule
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.getType(SyntacticSequencerPDAProvider.java:703)
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.createEmitterStates(SyntacticSequencerPDAProvider.java:605)
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.createAbsorberState(SyntacticSequencerPDAProvider.java:574)
        at org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.getSyntacticSequencerPDAs(SyntacticSequencerPDAProvider.java:631)
        at org.eclipse.xtext.serializer.analysis.SemanticSequencerNfaProvider.getSemanticSequencerNFAs(SemanticSequencerNfaProvider.java:240)
        at org.eclipse.xtext.serializer.analysis.GrammarConstraintProvider.getConstraints(GrammarConstraintProvider.java:624)
        at org.eclipse.xtext.xtext.generator.serializer.SemanticSequencerExtensions.getGrammarConstraints(SemanticSequencerExtensions.java:112)
        at org.eclipse.xtext.xtext.generator.serializer.SerializerFragment2.generateAbstractSemanticSequencer(SerializerFragment2.java:417)
        at org.eclipse.xtext.xtext.generator.serializer.SerializerFragment2.generate(SerializerFragment2.java:211)
        at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:43)
        at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:228)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:133)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:35)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:213)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:38)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:21)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:103)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by cdietrich** [comment]
i also wonder if the clone methods in the SyntacticSequencerPDAProvider are bogus. maybe it should load all supergrammars into the clone

**Comment by cdietrich** [comment]
diffs in normalizationMaps

```
{platform:/resource/org.xtext.example.mydsl/src/org/xtext/example/base2/Base2.xtext=platform:/resource/org.xtext.example.mydsl/src/org/xtext/example/base2/Base2.xtext, file:/home/dietrich/eclipse-workspaces/202212m3/org.eclipse.xtext/bin/org/eclipse/xtext/common/Terminals.xtext=file:/home/dietrich/eclipse-workspaces/202212m3/org.eclipse.xtext/bin/org/eclipse/xtext/common/Terminals.xtext, file:/home/dietrich/Downloads/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/target/classes/org/xtext/example/base/Base.xtext=file:/home/dietrich/Downloads/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/target/classes/org/xtext/example/base/Base.xtext, http://www.xtext.org/example/base/MyBase=http://www.xtext.org/example/base/MyBase, http://www.xtext.org/example/base/MyBase2=http://www.xtext.org/example/base/MyBase2}

{platform:/resource/org.xtext.example.mydsl/src/org/xtext/example/base2/Base2.xtext=platform:/resource/org.xtext.example.mydsl/src/org/xtext/example/base2/Base2.xtext}
```

**Comment by S-wald** [comment]
The problem can be solved by putting the src-folder as an additionalClassPathElement inside the configuration of the mwe2Launcher executions in the pom.xml:
```
<additionalClasspathElements>
  <additionalClasspathElement>${project.basedir}/src</additionalClasspathElement>
</additionalClasspathElements>
```

**Comment by cdietrich** [comment]
we should think about this anyway. cc @szarnekow
