### ISSUE TITLE
[serializer] SyntacticSequencerPDAProvider.SynTransition.getAmbiguousSyntaxes() is not thread-safe

### ISSUE THREAD

**Issue by franzbecker** [eclipse/xtext-core#203]
# Problem description

In my projects I often do some generation / serialization in public (all proxies resolved, no problems with EMF there).

There is a hard to reproduce multi-threading issue in the above mentioned method that manifests itself in the following exception:
```
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.xtext.example.mydsl.serializer.MyDslSyntacticSequencer.emitUnassignedTokens(MyDslSyntacticSequencer.java:43)
	at org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer.navigateToAbsorber(AbstractSyntacticSequencer.java:463)
	at org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer.acceptAssignedTerminal(AbstractSyntacticSequencer.java:224)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptRuleCall(SequenceFeeder.java:356)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:239)
	at org.xtext.example.mydsl.serializer.MyDslSemanticSequencer.sequence_VarcharType(MyDslSemanticSequencer.java:72)
	at org.xtext.example.mydsl.serializer.MyDslSemanticSequencer.sequence(MyDslSemanticSequencer.java:40)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptEObjectRuleCall(SequenceFeeder.java:325)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptRuleCall(SequenceFeeder.java:352)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:263)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:412)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:478)
	at org.xtext.example.mydsl.serializer.MyDslSemanticSequencer.sequence_Model(MyDslSemanticSequencer.java:55)
	at org.xtext.example.mydsl.serializer.MyDslSemanticSequencer.sequence(MyDslSemanticSequencer.java:37)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:118)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:142)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:192)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:58)
```

# Problem analysis

The current implementation looks like this:
```
// from org.eclipse.xtext.serializer.analysis.SyntacticSequencerPDAProvider.SynTransition.getAmbiguousSyntaxes()
public List<AbstractElementAlias> getAmbiguousSyntaxes() {
    if (ambiguousSyntaxes != null)
        return ambiguousSyntaxes;
    if (!isSyntacticallyAmbiguous())
        return ambiguousSyntaxes = Collections.emptyList();
    ambiguousSyntaxes = Lists.newArrayList();
    AbstractElementAlias syntax = getAmbiguousSyntax();
    if (syntax instanceof GroupAlias) {
        GroupAlias group = (GroupAlias) syntax;
        for (AbstractElementAlias child : group.getChildren())
            if (child.isMany() || child.isOptional() || child instanceof AlternativeAlias)
                ambiguousSyntaxes.add(child);
    } else
        ambiguousSyntaxes.add(syntax);
    return ambiguousSyntaxes;
}
```

The cause of the `ConcurrentModificationException` is that the line `ambiguousSyntaxes = Lists.newArrayList();` assigns the list of ambiguous syntax elements before it is initialized.

Imagine there are 3 elements that need to go into that list. Thread 1 goes ahead and starts filling this list while thread 2 sees that the list is already there and starts iterating over it in the `emitUnassignedTokens`. If thread 1 did not finish the initialization before the iteration starts, the `ConcurrentModificationException` will occur. It might also happen that the list is initialized twice, in case both lists have already passed the null check but not set the instance variable yet.

# Possible solutions

The assignment `ambiguousSyntaxes = Lists.newArrayList()` may not happen until it is initialized, otherwise the whole method would need to be synchronized.

Therefore, one could do the following:
```
public List<AbstractElementAlias> getAmbiguousSyntaxes() {
    ...
    List<AbstractElementAlias> ambiguousSyntaxes = Lists.newArrayList();
    AbstractElementAlias syntax = getAmbiguousSyntax();
    ...
    this.ambiguousSyntaxes = ambiguousSyntaxes;
    return ambiguousSyntaxes;
}
```
This way it might still happen that the list is initialized twice. I don't have enough knowledge of the code base to say whether or not this is a problem. If this should be avoided, we need to introduce a synchronized clause like this:
```
public List<AbstractElementAlias> getAmbiguousSyntaxes() {
    if (ambiguousSyntaxes != null) {
        return ambiguousSyntaxes;
    }
    synchronized(this) {
       if (ambiguousSyntaxes != null) {
           return ambiguousSyntaxes;
       }
       ambiguousSyntaxes = createAmbiguousSyntaxes();
    }
}

private List<AbstractElementAlias> createAmbiguousSyntaxes() {
   ...
}

```

Note that there might be other methods that might need to be reworked as well which I did not analyze here, such as `SynTransition.getAmbiguousSyntax()` (without the plural).

# Example

I created a minimal example here: https://github.com/franzbecker/xtext-serializer-parallel-problem

The test that can reproduce this error (might need 10 or more attempts) is `MyDslParallelSerializingTest.serializeParallelAfterInitialization()`

The other test in this class (serializeParallel) demonstrates how parallel serialization fails if no serialization has been performed in the context of the injector yet.

**Comment by kthoms** [comment]
Thanks for the analysis, it was good to follow. I think the second approach looks cleaner, although I'm not sure if double computation would harm much. It is clearer that the initialization should happen only once. As you pointed out there might be other similar situations that get uncovered afterwards.
Please create a PR for the second approach.

**Comment by meysholdt** [comment]
no, please don't create a PR for the second approach. Sorry for the late response.

I'm not in favor of introducing slow synchronization code that is a burden even to users to don't use the serializer in a multi-threaded environment.

An easy approach to resolve the issue is to run all static initialization in a single thread *before* running the actual serialization in a multi-threaded environment. This way, no expensive synchronization is needed because the actual serialization does not mutated the shared state.
