### ISSUE TITLE
[formatting2] `RegionsOutsideFrameException.getMessage` throws `StringIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xtext-core#2055]
Some of my unit tests for formatting are crashing ungracefully because the `getMessage` method of an exception being thrown (`RegionsOutsideFrameException`) is, itself, throwing a `StringIndexOutOfBoundsException`.

Because of this, it is actually `junit5` that is crashing, not the unit test itself. View in Eclipse:
![image](https://user-images.githubusercontent.com/47859223/212915334-b9a98448-6a91-4915-b7c8-74ea27d17c71.png)

Stack trace in console:
```
WARNING: TestExecutionListener [org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener] threw exception for method: executionFinished(TestIdentifier [uniqueId = [engine:junit-jupiter]/[class:com.regnosys.rosetta.formatting2.RosettaExpressionFormattingTest]/[method:testShortUnaryOperation1()], parentId = [engine:junit-jupiter]/[class:com.regnosys.rosetta.formatting2.RosettaExpressionFormattingTest], displayName = 'testShortUnaryOperation1()', legacyReportingName = 'testShortUnaryOperation1()', source = MethodSource [className = 'com.regnosys.rosetta.formatting2.RosettaExpressionFormattingTest', methodName = 'testShortUnaryOperation1', methodParameterTypes = ''], tags = [], type = TEST], TestExecutionResult [status = FAILED, throwable = org.eclipse.xtext.formatting2.internal.RegionsOutsideFrameException@45be689c])
java.lang.StringIndexOutOfBoundsException: begin 60, end 62, length 60
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at java.base/java.lang.String.subSequence(String.java:1913)
	at org.eclipse.xtext.formatting2.regionaccess.internal.TextRegionRewriter.renderToAppendable(TextRegionRewriter.java:48)
	at org.eclipse.xtext.formatting2.regionaccess.internal.TextRegionRewriter.renderToString(TextRegionRewriter.java:71)
	at org.eclipse.xtext.formatting2.debug.TextRegionsWithTitleToString.toString(TextRegionsWithTitleToString.java:155)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at org.eclipse.xtext.formatting2.internal.RegionsOutsideFrameException.getMessage(RegionsOutsideFrameException.java:55)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintWriter.println(PrintWriter.java:837)
	at java.base/java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:768)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:725)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener.getTrace(JUnit5TestListener.java:100)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener.notifyIfNotSuccessful(JUnit5TestListener.java:88)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestListener.executionFinished(JUnit5TestListener.java:71)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$executionFinished$10(CompositeTestExecutionListener.java:69)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$notifyEach$19(CompositeTestExecutionListener.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.notifyEach(CompositeTestExecutionListener.java:93)
	at org.junit.platform.launcher.core.CompositeTestExecutionListener.executionFinished(CompositeTestExecutionListener.java:69)
	at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
	at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
	at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.executionFinished(OutcomeDelayingEngineExecutionListener.java:63)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:195)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by cdietrich** [comment]
can you please provide a minimal reproducing grammar + formatter + test

**Comment by SimonCockx** [comment]
@cdietrich Minimal repro:

https://github.com/REGnosys/rosetta-dsl/tree/formatting-bug

(i.e., on the `formatting-bug` branch of the `rosetta-dsl` repo)

Grammar:
```
grammar com.regnosys.rosetta.Rosetta with org.eclipse.xtext.common.Terminals
import "http://www.rosetta-model.com/RosettaExpression"

Expression returns RosettaExpression:
	ExistsExpression
;

ExistsExpression returns RosettaExpression:
	RosettaBooleanLiteral
	(
		=>(
			({RosettaExistsExpression.argument=current} 'exists')
			
		)
	)*
;

RosettaBooleanLiteral:
	value?='True' | {RosettaBooleanLiteral} 'False'
;
```

Formatter:
```
class RosettaFormatter extends AbstractFormatter2 {	
	def dispatch void format(RosettaExistsExpression expr, extension IFormattableDocument document) {		
		expr.formatConditionally(
			[extension doc |
				set(
					expr.argument.nextHiddenRegion,
					expr.nextHiddenRegion,
					[indent]
				)
			]
		)
	}
}
```

Test:
```
@ExtendWith(InjectionExtension)
@InjectWith(RosettaInjectorProvider)
class RosettaExpressionFormattingTest {
	@Inject
	extension FormatterTestHelper
	
	@Test
	def void testIndexOutOfBounds() {
		assertFormatted[
			it.toBeFormatted = '''
			True exists
			'''
		]
	}
}
```

**Comment by cdietrich** [comment]
unfortunately i have no clue what in the text region formatting toString goes wrong here.
what do you want to achieve in the formatter?

**Comment by SimonCockx** [comment]
Well, currently the `formatConditionally` is not really useful because I tried to cut down for the minimal repro.

I guess this issue is not really about having a correct formatter, but about providing a useful error message whenever you do something wrong with it, so in that sense the content of the formatter is not important.

However, I would welcome a workaround for my situation of course. :) It used to be like this:
```
private def void formatUnaryOperation(RosettaUnaryOperation expr, extension IFormattableDocument document, (IFormattableDocument) => void internalFormatter) {
		val afterArgument = expr.argument.nextHiddenRegion

		expr.formatConditionally(
			[doc | // case: short operation
				val extension singleLineDoc = doc.requireFitsInLine
				afterArgument
					.set[oneSpace]
				set(
					afterArgument,
					expr.nextHiddenRegion,
					[indent]
				)
				expr.argument.formatExpression(singleLineDoc)
				internalFormatter.apply(singleLineDoc)
			],
			[extension doc | // case: long operation
				afterArgument
					.set[newLine]
				set(
					afterArgument,
					expr.nextHiddenRegion,
					[indent]
				)
				expr.argument.formatExpression(doc)
				internalFormatter.apply(doc)
			]
		)
	}
```
What I intended this to do:
- if it fits on one line, put a single space between the operand and the operator.
- if it doesn't, put a single new line between the operand and the operator, and also indent.
In both cases: also format the operand and do some custom logic depending on which operation I'm formatting (`internalFormatter`).

Example of single line fit:
```
True exists exists
```
Example of multi-line formatting:
```
True
  exists
  exists
```

Looking back, you might note that indenting in the case of the single line is actually not doing anything useful, but it's what I wrote at the moment.

I suspect that the original error is being thrown because `expr.nextHiddenRegion` (the region where I decrease indentation) is outside of the semantic region of `expr`. I'm not sure whether it is possible to include that region in the conditional formatting somehow?

Before, I actually tried putting the indentation outside of the conditional formatting, but this lead to a strange indentation issue for some cases where the indentation started inside a subdocument created elsewhere and ended outside this subdocument. (I'm not sure if that's relevant, but if so, I can try to replicate that issue as well)

**Comment by cdietrich** [comment]
i fear you need to start debugging into the formatter and check what goes wrong. i wont find the time

**Comment by cdietrich** [comment]
the problem might be the trailing newline at the end of the text in the test
and the improper handling of that in 
org.eclipse.xtext.formatting2.regionaccess.internal.TextRegions.expandToLines(ITextSegment, int, int)
org.eclipse.xtext.formatting2.debug.TextRegionsWithTitleToString.getFrame()

**Comment by cdietrich** [comment]
the question is what would a naive patch like 
```
@Override
	public ILineRegion getNextLine() {
		ITextRegionAccess access = getTextRegionAccess();
		int start = getEndOffset() + 1;
		String text = access.regionForDocument().getText();
		while (true) {
			if (start > text.length())
				return null;
			if (start == text.length())
				return new LineRegion(access, start, 0);
			char c = text.charAt(start);
```

**Comment by cdietrich** [comment]
@meysholdt is it intentional we dont create a (empty) line region for empty line at end as of now?

**Comment by SimonCockx** [comment]
> the problem might be the trailing newline at the end of the text in the test

Removing the newline indeed made the test succeed! (actually I was expecting an error to be thrown, so I don't completely get it)

**Comment by cdietrich** [comment]
in our (xtext internal) tests we seem to do a lot of trimming
![Bildschirmfoto vom 2023-01-18 09-22-57](https://user-images.githubusercontent.com/238736/213120290-9fc61d9b-7fe4-42d8-83cd-bd08a76b56d1.png)

**Comment by cdietrich** [comment]
@SimonCockx can you also try my patch?

**Comment by SimonCockx** [comment]
I'll try to test it today. If not tomorrow.

**Comment by SimonCockx** [comment]
@cdietrich I'm not sure about the best approach of testing your patch. Is there a way to replace the Xtext dependency in the target platform with the GitHub branch you're working on?

**Comment by cdietrich** [comment]
are you in eclipse plugins or pure maven/gradle?

**Comment by SimonCockx** [comment]
Eclipse plugins (with Maven)

**Comment by cdietrich** [comment]
in the plugins-view you will find org.eclipse.xtext and org.eclipse.xtext.util
you can rightclick them and select import as source plugin.
then you an patch the class manually

**Comment by SimonCockx** [comment]
Hm, I tried it, but I need some more manual setup it seems. The imported projects need are getting 18000+ errors of types not being resolved (e.g., `The import org.eclipse.emf cannot be resolved`)

**Comment by cdietrich** [comment]
so you dont have a normal maven project tycho but a pure maven project?

**Comment by SimonCockx** [comment]
No, I do use Tycho. See my repro: https://github.com/REGnosys/rosetta-dsl/tree/formatting-bug.

Maybe I'm missing some dependency in the target platform? Not sure.

**Comment by cdietrich** [comment]
what is error on manifest.mf?

**Comment by SimonCockx** [comment]
In the Xtext project? One error: `Unsatisfied constraint: 'Import-Package: org.apache.log4j; version="1.2.24"'`

**Comment by cdietrich** [comment]
are you sure you did NOT select import from git but import as source?

**Comment by SimonCockx** [comment]
Got it in another way (https://stackoverflow.com/questions/39941850/eclipse-import-a-plugin-as-source-project-but-its-not-include-src-folder)

**Comment by cdietrich** [comment]
i mean the plug-ins view not the package explorer
(window show view)

**Comment by SimonCockx** [comment]
I can confirm that your patch works! Thanks!

I'm succesfully getting a `RegionsOutsideFrameException` :)
