### ISSUE TITLE
NPE in NodeModelUtils.findLeafNodeAtOffset

### ISSUE THREAD

**Issue by rubenporras** [eclipse/xtext-core#2070]
java.lang.NullPointerException: Cannot invoke "org.eclipse.xtext.nodemodel.INode.getParent()" because "localNode" is null
	at org.eclipse.xtext.nodemodel.util.NodeModelUtils.findLeafNodeAtOffset(NodeModelUtils.java:73)
	at org.eclipse.xtext.resource.EObjectAtOffsetHelper.getElementWithNameAt(EObjectAtOffsetHelper.java:184)
	...
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$definition$24(LanguageServerImpl.java:610)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by szarnekow** [comment]
Closed as per the comment in the closed merge request #2069
