### ISSUE TITLE
[Wizard] General: Gradle Tests dont work

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#224]
create a new project using wizard and choose e.g. web + plain + gradle

./gradlew build gives

```
com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.eclipse.xtext.common.TerminalsStandaloneSetupGenerated.createInjector(TerminalsStandaloneSetupGenerated.java:40)
	at org.eclipse.xtext.common.TerminalsStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(TerminalsStandaloneSetupGenerated.java:34)
	at org.eclipse.xtext.common.TerminalsStandaloneSetup.doSetup(TerminalsStandaloneSetup.java:11)
	at org.xtext.example.mydsl1.MyDslStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(MyDslStandaloneSetupGenerated.java:21)
	at org.xtext.example.mydsl1.tests.MyDslInjectorProvider.internalCreateInjector(MyDslInjectorProvider.java:41)
	at org.xtext.example.mydsl1.tests.MyDslInjectorProvider.getInjector(MyDslInjectorProvider.java:29)
	at org.xtext.example.mydsl1.tests.MyDslInjectorProvider.setupRegistry(MyDslInjectorProvider.java:63)
	at org.eclipse.xtext.testing.XtextRunner.methodBlock(XtextRunner.java:43)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 40 more
Caused by: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:96)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:845)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 50 more


```

**Comment by cdietrich** [comment]
equinox common seems on the classpath twice. once in  3.8.0 and once in 3.6.0

**Comment by cdietrich** [comment]
``` 
testCompile - Dependencies for source set 'test'.
+--- project :org.xtext.example.mydsl1
|    +--- org.eclipse.xtext:org.eclipse.xtext:2.11.0-SNAPSHOT
|    |    +--- org.eclipse.xtext:org.eclipse.xtext.util:2.11.0-SNAPSHOT
|    |    |    +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.11.0-SNAPSHOT
|    |    |    |    +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.11.0-SNAPSHOT
|    |    |    |    |    \--- com.google.guava:guava:[14.0,19) -> 18.0
|    |    |    |    \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.11.0-SNAPSHOT
|    |    |    |         \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.11.0-SNAPSHOT (*)
|    |    |    +--- log4j:log4j:1.2.16
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.common:[2.10.1,3) -> 2.12.0
|    |    |    +--- org.eclipse.emf:org.eclipse.emf.ecore:[2.10.2,3) -> 2.12.0
|    |    |    \--- com.google.inject:guice:3.0
|    |    |         +--- javax.inject:javax.inject:1
|    |    |         \--- aopalliance:aopalliance:1.0
|    |    +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.11.0-SNAPSHOT (*)
|    |    +--- log4j:log4j:1.2.16
|    |    +--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
|    |    +--- org.eclipse.emf:org.eclipse.emf.common:[2.10.1,3) -> 2.12.0
|    |    +--- org.eclipse.emf:org.eclipse.emf.ecore.xmi:[2.10.2,3) -> 2.12.0
|    |    +--- com.google.inject:guice:3.0 (*)
|    |    \--- org.antlr:antlr-runtime:3.2
|    \--- org.eclipse.xtext:org.eclipse.xtext.xbase:2.11.0-SNAPSHOT
|         \--- org.eclipse.xtext:org.eclipse.xtext.common.types:2.11.0-SNAPSHOT
|              +--- org.eclipse.xtext:org.eclipse.xtext:2.11.0-SNAPSHOT (*)
|              \--- org.ow2.asm:asm-commons:5.0.1
|                   \--- org.ow2.asm:asm-tree:5.0.1
|                        \--- org.ow2.asm:asm:5.0.1
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
+--- org.eclipse.xtext:org.eclipse.xtext.testing:2.11.0-SNAPSHOT
|    +--- org.eclipse.xtext:org.eclipse.xtext:2.11.0-SNAPSHOT (*)
|    +--- org.eclipse.xtext:org.eclipse.xtext.ide:2.11.0-SNAPSHOT
|    |    +--- org.eclipse.xtext:org.eclipse.xtext:2.11.0-SNAPSHOT (*)
|    |    \--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.1.0-SNAPSHOT
|    |         +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.1.0-SNAPSHOT
|    |         |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.1.0-SNAPSHOT
|    |         |    |    +--- com.google.guava:guava:[14.0,19) -> 18.0
|    |         |    |    \--- com.google.code.gson:gson:2.7
|    |         |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:2.10.0 -> 2.11.0-SNAPSHOT (*)
|    |         \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.1.0-SNAPSHOT (*)
|    \--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.1.0-SNAPSHOT (*)
\--- org.eclipse.xtext:org.eclipse.xtext.xbase.testing:2.11.0-SNAPSHOT
     +--- org.eclipse.xtext:org.eclipse.xtext.xbase:2.11.0-SNAPSHOT (*)
     +--- junit:junit:4.12 (*)
     \--- org.eclipse.jdt:org.eclipse.jdt.core:[3.6.0,4) -> 3.12.2
          +--- org.eclipse.platform:org.eclipse.core.resources:[3.3.0,4.0.0) -> 3.11.1
          |    +--- org.eclipse.platform:org.eclipse.core.expressions:[3.2.0,4.0.0) -> 3.5.100
          |    |    \--- org.eclipse.platform:org.eclipse.core.runtime:[3.3.0,4.0.0) -> 3.12.0
          |    |         +--- org.eclipse.platform:org.eclipse.osgi:[3.7.0,4.0.0) -> 3.11.2
          |    |         +--- org.eclipse.platform:org.eclipse.equinox.common:[3.8.0,4.0.0) -> 3.8.0
          |    |         +--- org.eclipse.platform:org.eclipse.core.jobs:[3.2.0,4.0.0) -> 3.8.0
          |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.8.0,4.0.0) -> 3.8.0
          |    |         +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.4.0,4.0.0) -> 3.6.100
          |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.7.0,4.0.0) -> 3.8.0
          |    |         +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.4.0,4.0.0) -> 3.6.1
          |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
          |    |         +--- org.eclipse.platform:org.eclipse.core.contenttype:[3.3.0,4.0.0) -> 3.5.100
          |    |         |    +--- org.eclipse.platform:org.eclipse.equinox.preferences:[3.2.0,4.0.0) -> 3.6.1 (*)
          |    |         |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.2.0,4.0.0) -> 3.6.100 (*)
          |    |         |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
          |    |         \--- org.eclipse.platform:org.eclipse.equinox.app:[1.0.0,) -> 1.3.400
          |    |              +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.4.0,4.0.0) -> 3.6.100 (*)
          |    |              \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
          |    +--- org.eclipse.platform:org.eclipse.core.filesystem:[1.3.0,2.0.0) -> 1.6.1
          |    |    +--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
          |    |    +--- org.eclipse.platform:org.eclipse.equinox.registry:[3.2.0,4.0.0) -> 3.6.100 (*)
          |    |    \--- org.eclipse.platform:org.eclipse.osgi:[3.2.0,4.0.0) -> 3.11.2
          |    \--- org.eclipse.platform:org.eclipse.core.runtime:[3.12.0,4.0.0) -> 3.12.0 (*)
          +--- org.eclipse.platform:org.eclipse.core.runtime:[3.3.0,4.0.0) -> 3.12.0 (*)
          +--- org.eclipse.platform:org.eclipse.core.filesystem:[1.0.0,2.0.0) -> 1.6.1 (*)
          \--- org.eclipse.platform:org.eclipse.text:[3.1.0,4.0.0) -> 3.6.0
               +--- org.eclipse.platform:org.eclipse.core.commands:[3.5.0,4.0.0) -> 3.8.0
               |    \--- org.eclipse.platform:org.eclipse.equinox.common:[3.2.0,4.0.0) -> 3.8.0
               \--- org.eclipse.platform:org.eclipse.equinox.common:[3.5.0,4.0.0) -> 3.8.0
```

**Comment by cdietrich** [comment]
@spoenemann do you have an idea how to resolve this?

**Comment by holgerschill** [comment]
Wouldn't it help to use org.eclipse.equinox.common 3.8.0 for Xtext as well?

**Comment by holgerschill** [comment]
xtext-core/gradle/versions.gradle want's '3.5.0.v20100503'

**Comment by cdietrich** [comment]
that equnixRegistry

'equinoxCommon' : '3.6.0',

**Comment by holgerschill** [comment]
Right

**Comment by holgerschill** [comment]
* What went wrong:
Could not resolve all dependencies for configuration ':org.eclipse.xtext:compileClasspath'.
> Could not find any version that matches org.eclipse.equinox:org.eclipse.equinox.common:[3.8.0, 4.0.0].
  Versions that do not match:
      3.6.200.v20130402-1505
      3.6.0
      3.6.0.v20100503
  Searched in the following locations:
      https://jcenter.bintray.com/org/eclipse/equinox/org.eclipse.equinox.common/maven-metadata.xml
      file:/Users/schill/.m2/repository/org/eclipse/equinox/org.eclipse.equinox.common/maven-metadata.xml
      file:/Users/schill/.m2/repository/org/eclipse/equinox/org.eclipse.equinox.common/
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/equinox/org.eclipse.equinox.common/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/equinox/org.eclipse.equinox.common/
  Required by:
      project :org.eclipse.xtext

**Comment by cdietrich** [comment]
but where does the 3.8.0 come from?

**Comment by spoenemann** [comment]
They changed the group id: we use
```
org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
```
and JDT uses
```
org.eclipse.platform:org.eclipse.equinox.common:3.8.0
```

**Comment by cdietrich** [comment]
Download https://jcenter.bintray.com/org/eclipse/platform/org.eclipse.equinox.common/3.8.0/org.eclipse.equinox.common-3.8.0.pom

**Comment by holgerschill** [comment]
So is that a problem to us to switch to 3.8.0?

**Comment by cdietrich** [comment]
+ change the groupid

**Comment by holgerschill** [comment]
groupid an version as 3.6.0 is curved in stone currently [3.8.0,4.0.0] should work. Build runs locally.

**Comment by spoenemann** [comment]
Ok, let's change our dependency in `org.eclipse.xtext` to the new group id and use the same version range as JDT.

**Comment by cdietrich** [comment]
hmmm seems that does not work in the first place http://services.typefox.io/open-source/jenkins/job/xtext-core/job/hs%252Fissue224/2/testReport/junit/org.eclipse.xtext.ide.tests.editor.contentassist/ContentAssistContextFactoryTest/classMethod/

**Comment by holgerschill** [comment]
Problem is not fixed:
see http://services.typefox.io/open-source/jenkins/job/xtext-core/job/hsIssue224/2/

**Comment by spoenemann** [comment]
We should also lift the minimum dependency to jdt.core to version `3.12.2` in order to avoid conflicts with the older platform bundles required by earlier jdt.core versions. Needs to be done in xtext-extras and xtext-xtend.

**Comment by cdietrich** [comment]
might this be connected to the maven stuff as well
https://github.com/eclipse/xtext-xtend/blob/a69ae8f519a2f60df2ea80cf01205b6a666429dc/releng/org.eclipse.xtend.maven.parent/pom.xml

**Comment by spoenemann** [comment]
Yes, the dependencies and versions used there must be consistent with those in the Gradle builds.

**Comment by cdietrich** [comment]
@holgerschill @spoenemann changes done to xtext-core look promising, leaves the jdt stuff (needs to be done in extras and xtend as well) + the maven versions

**Comment by spoenemann** [comment]
I don't think we have these kinds of problems (package splitting with differently signed jars) in the p2 world. As long as we don't encounter any specific problems due to changed APIs or so, we can leave the minimum versions as they are.

**Comment by cdietrich** [comment]
so we "hope" for not using new api?

**Comment by kthoms** [comment]
> We should also lift the minimum dependency to jdt.core to version 3.12.2 in order to avoid conflicts with the older platform bundles required by earlier jdt.core versions.
3.12.2 is the latest Neon version. Doesn't this break backward compatibilty with Luna?

**Comment by cdietrich** [comment]
Well I think the idea is to do this on gradle and maven side only and leave eclipse / manifests as is and hope for the best

**Comment by kthoms** [comment]
So I don't see what has to be done for the Oomph setup. The user can select the base target (Luna etc.) which includes JDT in the appropriate version.

**Comment by holgerschill** [comment]
I pushed :
https://github.com/eclipse/xtext-extras/pull/99
https://github.com/eclipse/xtext-eclipse/pull/152
https://github.com/eclipse/xtext-umbrella/pull/15
https://github.com/eclipse/xtext-maven/pull/8
https://github.com/eclipse/xtext-xtend/pull/117

**Comment by spoenemann** [comment]
> so we "hope" for not using new api?

The only alternative I see would be to restrict ourselves to the older jdt.core 3.10 version and keep the equinox.common version 3.6 as before. But I think sooner or later that would lead to problems since the signing is incompatible with the current releases. So we need to keep this in mind and be very careful when we change code that depends on JDT (watch out for `@since` tags when using API).

**Comment by svenefftinge** [comment]
Is this issue resolved now?

**Comment by cdietrich** [comment]
could not test yet

**Comment by cdietrich** [comment]
looks good 👍
