### ISSUE TITLE
Never call inputstream.reset() when it's not supported

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#239]
See JavaDoc from 
java.io.InputStream.reset()
about when calls are allowed.

```
org.eclipse.xtext.util.RuntimeIOException: java.io.IOException: mark/reset not supported
at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.generateFile(EclipseResourceFileSystemAccess2.java:280)
at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.generateFile(EclipseResourceFileSystemAccess2.java:237)
(…)
Caused by: java.io.IOException: mark/reset not supported
at java.io.InputStream.reset(Unknown Source)
at org.eclipse.xtext.builder.EclipseResourceFileSystemAccess2.generateFile(EclipseResourceFileSystemAccess2.java:253)
... 32 more
```

**Comment by meysholdt** [comment]
this actually belongs to eclipse/xtext-eclipse

**Comment by spoenemann** [comment]
The problem occurs with `java.nio.channels.Channels.newInputStream(ReadableByteChannel)`, which uses a `sun.nio.ch.ChannelInputStream`.
