### ISSUE TITLE
ConcurrentModificationException in ClusteringBuilder#doUpdate

### ISSUE THREAD

**Issue by kduske-n4** [eclipse/xtext-core#268]
Hi all,

we have experienced a `ConcurrentModificationException` several times when running long builds as part of our tests. At first, this happened when calling [QueuedBuildData#getAllRemainingURIs](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/QueuedBuildData.java#L346) from our code to create a debug logging message in [this method](https://github.com/NumberFour/n4js/blob/master/plugins/eu.numberfour.n4js.ui/src/eu/numberfour/n4js/ui/building/N4JSGenerateImmediatelyBuilderState.java#L198).

The result of calling `getAllRemainingURIs` is an `Iterable<URI>` which is consumed immediately when the log message is built.

Here's the entire stacktrace:

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.base.Joiner.appendTo(Joiner.java:109)
	at com.google.common.base.Joiner.appendTo(Joiner.java:152)
	at com.google.common.collect.Iterators.toString(Iterators.java:283)
	at com.google.common.collect.Iterables.toString(Iterables.java:275)
	at com.google.common.collect.FluentIterable.toString(FluentIterable.java:118)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.logBuildData(N4JSGenerateImmediatelyBuilderState.java:208)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:174)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.run(ExternalLibraryBuilderHelper.java:426)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.access$3(ExternalLibraryBuilderHelper.java:378)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.doPerformOperation(ExternalLibraryBuilderHelper.java:276)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:173)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:161)
	at eu.numberfour.n4js.external.ExternalLibrariesReloadHelper.reloadLibraries(ExternalLibrariesReloadHelper.java:110)
	at eu.numberfour.n4js.n4.tests.realworld.FabelhaftSnapshotIntegrationPluginTestLowMemory.downloadNpmDependencies(FabelhaftSnapshotIntegrationPluginTestLowMemory.java:198)
	at eu.numberfour.n4js.n4.tests.realworld.FabelhaftSnapshotIntegrationPluginTestLowMemory.configureBuiltIns(FabelhaftSnapshotIntegrationPluginTestLowMemory.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)
```

As you can see, we commented out the entire body of `logBuildData` to avoid this error, but it's still happening occasionally. Here's a more recent stacktrace:

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:149)
	at eu.numberfour.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:188)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.run(ExternalLibraryBuilderHelper.java:426)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper$BuildOperation.access$3(ExternalLibraryBuilderHelper.java:378)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.doPerformOperation(ExternalLibraryBuilderHelper.java:276)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:173)
	at eu.numberfour.n4js.external.ExternalLibraryBuilderHelper.build(ExternalLibraryBuilderHelper.java:161)
	at eu.numberfour.n4js.external.ExternalLibrariesReloadHelper.reloadLibraries(ExternalLibrariesReloadHelper.java:110)
	at eu.numberfour.n4js.n4.tests.realworld.FabelhaftSnapshotIntegrationPluginTestLowMemory.downloadNpmDependencies(FabelhaftSnapshotIntegrationPluginTestLowMemory.java:198)
	at eu.numberfour.n4js.n4.tests.realworld.FabelhaftSnapshotIntegrationPluginTestLowMemory.configureBuiltIns(FabelhaftSnapshotIntegrationPluginTestLowMemory.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)
```

I'm not sure whether or not this is a threading issue. But several methods of `QueuedBuilderState` are synchronized, which leads me to assume that this class is sometimes used concurrently.

Note that the second stacktrace also involves `getAllRemainingURIs`, which is called in [ClusteringBuilderState#doUpdate](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/ClusteringBuilderState.java#L149) as well.

**Comment by cdietrich** [comment]
it would be interesting to see the "other" guys acessing the stuff. in both traces it is the build itself which should be sequential. can you give some insights what ExternalLibraryBuilderHelper does?

**Comment by cdietrich** [comment]
i have found this very old one https://bugs.eclipse.org/bugs/show_bug.cgi?id=358349

**Comment by kduske-n4** [comment]
Hi @cdietrich, thanks for looking into this issue. It appears as if @svenefftinge already foresaw what is happening here (unsynchronized call to `getAllRemainingURIs`). From what I understand, `QueuedBuildData` relies on the assumption that the workspace is locked to prevent synchronization issues.

> Until now org.eclipse.xtext.builder.impl.QueuedBuildData.queueURI(URI) is only called from the builder context which uses a single thread and locks the entire working tree in the workspace.

I will check if our code violates that assumption somehow.

To answer your question: In N4JS, the IDE allows the user to install external dependencies in the form of NPM packages. These packages are built using `ExternalLibraryBuilderHelper`. As far as I can tell from the code, it does not use multiple threads at all.

**Comment by svenefftinge** [comment]
The QueuedBuildData is a shared singleton object, which is modified by the ClusteringBuilderState and UIResourceChangeRegistry. The `queueURI` nor the `getAllRemainingURIs`are synched, because they are implicitly synched by the workspace lock during builds. Seems like you are accessing the code outside of such a lock.

**Comment by szarnekow** [comment]
Problem was likely in N4JSGenerateImmediatelyBuilderState
