### ISSUE TITLE
The serializer is not able to determine the context

### ISSUE THREAD

**Issue by NiekHulsman** [eclipse/xtext-core#302]
The following grammar and test results in the following exception in Xtext 2.10.0:

See also: https://www.eclipse.org/forums/index.php/t/1084971/

```
at org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic$ExceptionThrowingAcceptor.accept(ISerializationDiagnostic.java:131)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:480)
	at expression.serializer.AbstractExpressionSemanticSequencer.sequence_AdditiveExpression_MultiplicativeExpression_PowerExpression(AbstractExpressionSemanticSequencer.java:245)
	at expression.serializer.AbstractExpressionSemanticSequencer.sequence(AbstractExpressionSemanticSequencer.java:82)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:118)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:142)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:192)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:58)
	at expression.SerializerTest.testSerializer(SerializerTest.java:49)
```

**Grammar:**

```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	greetings+=Greeting*;
	
Greeting:
	'Hello' expression=AdditiveExpression '!';
		
enum AdditiveOperator returns BinaryOperator: 
	PLUS='+' | MINUS='-' | CONCAT='&'
;

AdditiveExpression returns Expression:
	MultiplicativeExpression (
		=>({BinaryExpression.left=current}
		operator=AdditiveOperator)
		right=MultiplicativeExpression
	)*
;

enum MultiplicativeOperator returns BinaryOperator: 
	MULTIPLY='*' | DIVIDE='/' | MODULO='mod'
;

MultiplicativeExpression returns Expression:
	LiteralNumber (
		=>({BinaryExpression.left=current}
		operator=MultiplicativeOperator)
		right=LiteralNumber
	)*
;

LiteralNumber:
	value=INT
;
```

**Test**

```
package org.xtext.example.mydsl;

import org.eclipse.xtext.serializer.ISerializer;
import org.eclipse.xtext.util.EmfFormatter;
import org.testng.annotations.Test;
import org.xtext.example.mydsl.myDsl.BinaryExpression;
import org.xtext.example.mydsl.myDsl.BinaryOperator;
import org.xtext.example.mydsl.myDsl.Expression;
import org.xtext.example.mydsl.myDsl.LiteralNumber;
import org.xtext.example.mydsl.myDsl.MyDslFactory;

import com.google.inject.Inject;
import com.google.inject.Injector;

public class SerializerTest
{
	@Inject
	ISerializer serializer;
	
	@Test
	public void testSerializer()
	{
		Expression result = MyDslFactory.eINSTANCE.createLiteralNumber();
		((LiteralNumber)result).setValue(10);

		for (int i = 1; i < 3; i++)
		{			
			LiteralNumber literalNumber  = MyDslFactory.eINSTANCE.createLiteralNumber();
			literalNumber.setValue(5);

			BinaryExpression binaryExpression = MyDslFactory.eINSTANCE.createBinaryExpression();
			binaryExpression.setLeft(result);
			binaryExpression.setRight(literalNumber);
			binaryExpression.setOperator(BinaryOperator.PLUS);
			
			result = binaryExpression;
		}
		
        System.out.println(EmfFormatter.objToStr(result));
		
		MyDslStandaloneSetup standaloneSetup = new MyDslStandaloneSetup();
		Injector injector = standaloneSetup.createInjectorAndDoEMFRegistration();
		injector.injectMembers(this);
		
		String serializedExpression = serializer.serialize(result);		
		System.out.println(serializedExpression);
	}
}
```

**Comment by cdietrich** [comment]
problem can no longer be reproduced in xtext 2.14
