### ISSUE TITLE
NPE thrown when an LSP extension tries to read a document before initialize

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#378]
The following exception occurs when an LSP extension calls `ILanguageServerAccess.doRead(..)` before the `initialize` request has arrived. The WorkspaceManager should throw an IllegalStateException instead.
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.ide.server.WorkspaceManager.getProjectManager(WorkspaceManager.java:177)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:243)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:760)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runRead$2(RequestManager.java:116)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 5 more
```

**Comment by akosyakov** [comment]
Actually, the LSP declares how the server should handle such cases:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request
