### ISSUE TITLE
FormattableDocumentTest.autoWrapInsert fails on windows

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#417]
```
org.junit.ComparisonFailure: expected:<kwlist
kw1!kw2@[
]
> but was:<kwlist
kw1!kw2@[]
>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
```

**Comment by cdietrich** [comment]
Fixed in 2.13
