### ISSUE TITLE
LanguageServer textdocument/completion request not working on windows

### ISSUE THREAD

**Issue by chriskn** [eclipse/xtext-core#49]
```
Server Notification:
	{"method":"textDocument/publishDiagnostics","params":{"uri":"file:///c:/test/test.mydsl","diagnostics":[]},"jsonrpc":"2.0"}
Client Notification:
	{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///c%3A/test/test.mydsl","version":2},"contentChanges":[{"range":{"start":{"line":0,"character":9},"end":{"line":0,"character":10}},"rangeLength":1,"text":""}]}}
Client Request:
	{"jsonrpc":"2.0","id":1,"method":"textDocument/completion","params":{"textDocument":{"uri":"file:///c%3A/test/test.mydsl"},"position":{"line":0,"character":9}}}
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///c%3A/test/test.mydsl
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.eclipse.xtext.ide.server.UriExtensions.toUri(UriExtensions.java:23)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$18(LanguageServerImpl.java:441)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runRead$3(RequestManager.java:129)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Server Response:
	{"id":"1","error":{"code":-32603,"message":"java.nio.file.InvalidPathException:Illegal char \u003c:\u003e at index 4: file:///c%3A/test/test.mydsl"},"jsonrpc":"2.0"}
```

**Comment by cdietrich** [comment]
beside the problem in the uri handling, when fixing this 

```
  public URI toUri(final String path) {
    java.net.URI uri = java.net.URI.create(path);
    return URI.createURI(uri.getPath()); // getPath does a decode
  }
```

workspace/project service cannot handle it

```
        {"jsonrpc":"2.0","id":2,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///c%3A/work/xtext-languageserver-example/demo/a.mydsl"},"position":{"line":3,"character":9}}}
java.lang.NullPointerException
        at org.eclipse.xtext.ide.server.WorkspaceManager.getProjectManager(WorkspaceManager.java:154)
        at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:194)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$hover$27(LanguageServerImpl.java:697)
        at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runRead$3(RequestManager.java:129)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Server Response:
        {"id":"2","error":{"code":-32603,"message":"java.lang.NullPointerException:null"},"jsonrpc":"2.0"}
```

**Comment by cdietrich** [comment]
the second error is caused by the scanner. it should init uris differently
