### ISSUE TITLE
[Serializer] Add null guard

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#537]
When a null reference is passed into Serializer#serialize a NPE is raised in ConcreteSyntaxValidator. It would be better to check this invalid argument up front.

The stack trace shows:
```
java.lang.NullPointerException
	at org.eclipse.xtext.validation.impl.ConcreteSyntaxValidator.isEObjectTransient(ConcreteSyntaxValidator.java:88)
	at org.eclipse.xtext.validation.impl.ConcreteSyntaxValidator.validateObject(ConcreteSyntaxValidator.java:102)
	at org.eclipse.xtext.validation.impl.ConcreteSyntaxValidator.validateRecursive(ConcreteSyntaxValidator.java:148)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:126)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:192)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:58)

```

**Comment by cdietrich** [comment]
Fixed in 2.14
