### ISSUE TITLE
NPE in TokenSequencePreservingPartialParsingHelper.isBrokenPreviousState

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#600]
```
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.parser.TokenSequencePreservingPartialParsingHelper.isBrokenPreviousState(TokenSequencePreservingPartialParsingHelper.java:143)
	at org.eclipse.xtext.xbase.parser.TokenSequencePreservingPartialParsingHelper.reparse(TokenSequencePreservingPartialParsingHelper.java:74)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doReparse(AbstractAntlrParser.java:138)
	at org.eclipse.xtext.parser.AbstractParser.reparse(AbstractParser.java:50)
	at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:253)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:150)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:442)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:422)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:98)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
``` 

@szarnekow do you have any idea what could cause this. and should there be a null guard?

**Comment by cdietrich** [comment]
in the same ,log i see

```
Unexpected log from plugin: org.eclipse.core.jobs, message: 'An internal error occurred during: "calculating highlighting".'
java.lang.IllegalStateException: The resource should have no more than one root element, but: [xxx.impl.FplModelImpl@62e0f3d3, xxx.impl.FplModelImpl@5bb08add]
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:239)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler.beforeRefresh(HighlightingReconciler.java:361)
	at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler$2$1.exec(HighlightingReconciler.java:340)
	at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler$2$1.exec(HighlightingReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:98)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.syntaxcoloring.HighlightingReconciler$2.run(HighlightingReconciler.java:336)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by cdietrich** [comment]
additionally i see org.eclipse.emf.ecore.resource.impl.ResourceImpl.getContents() beeing null.
this seems to be a concurrency issue.

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=529574 as well

**Comment by cdietrich** [comment]
@szarnekow any idea what to do about this. unfortunately i dont know how to reproduce

**Comment by szarnekow** [comment]
The parse result can be null in general (though it's unlikely in a consistent setup). `isBrokenPreviousState` should certainly return true if the parse result is null. Is the second trace from the same user / language impl?

**Comment by cdietrich** [comment]
yes both traces were from the same eclipse instance

**Comment by szarnekow** [comment]
If there is a chance to contact the user, that could help. Looks like some customising / configuration is broken.

**Comment by cdietrich** [comment]
i saw this locally. but could not reproduce later.
