### ISSUE TITLE
RequestManagerTest is flaky

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#622]
java.util.concurrent.CompletionException: java.lang.AssertionError: expected:<1> but was:<0>
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at org.eclipse.xtext.ide.tests.server.concurrent.RequestManagerTest.testRunWriteAfterRead(RequestManagerTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.eclipse.xtext.ide.tests.server.concurrent.RequestManagerTest.lambda$testRunWriteAfterRead$14(RequestManagerTest.java:159)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

**Comment by cdietrich** [comment]
@akosyakov could this be connected to your recent change?

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-core/job/master/137/

**Comment by akosyakov** [comment]
@cdietrich yes, it is probably related, i will have a look this week, thanks for the link

**Comment by cdietrich** [comment]
still and issue

**Comment by cdietrich** [comment]
@szarnekow could you have a look

**Comment by szarnekow** [comment]
Bitten by this in practice. The reader is not finished when the writer starts. So we do have racy behaviour. I'll try to fix it.
```
	@Test
	def void testWriteWaitsForReadToFinish() throws Exception {
		val marked = new AtomicBoolean(false)
		val countDownInRead = new CountDownLatch(1)
		val countDownInWrite = new CountDownLatch(1)
		val proceedWithWrite = new CountDownLatch(1)
		val reader = requestManager.runRead [ cancelIndicator |
			countDownInRead.countDown
			Uninterruptibles.awaitUninterruptibly(countDownInWrite)
			marked.set(true)
			proceedWithWrite.countDown
			return null
		]
		Uninterruptibles.awaitUninterruptibly(countDownInRead)
		val writer = requestManager.runWrite( [], [ cancelIndicator, ignored |
			countDownInWrite.countDown
			Uninterruptibles.awaitUninterruptibly(proceedWithWrite)
			null
		])
		assertTrue(reader.isCancelled)
		try {
			Uninterruptibles.getUninterruptibly(writer, 1, TimeUnit.SECONDS)
			assertFalse(marked.get()) // this should not be the case
		} catch(TimeoutException e) {
			throw e
		}
	}
```
