### ISSUE TITLE
Generation not working on java 9/10 under eclipse 4.7.3a

### ISSUE THREAD

**Issue by nopecio** [eclipse/xtext-core#702]
When running the MWE2 file it gives:
[main] ERROR pes.access.impl.AbstractClassMirror  - resource is empty: java:/Objects/java.lang.Object
java.lang.IllegalStateException
	at org.eclipse.xtext.common.types.access.impl.AbstractClassMirror.getEObject(AbstractClassMirror.java:94)
	at org.eclipse.xtext.common.types.access.TypeResource.getEObject(TypeResource.java:94)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:205)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:261)

I added 
--add-modules=ALL-SYSTEM
--add-modules=java.se.ee
to eclipse .ini, but no luck.

Using xtext 2.13
Regards!

**Comment by cdietrich** [comment]
nopecio whichg version do you use?
java 9 works only with the current 2.14.0-SNAPSHOT
and java 10 is in work under
https://github.com/eclipse/xtext/issues/1177

**Comment by nopecio** [comment]
Thank you!
i miss understood the  support for java 9 in 2.13!
I'll give it a try!

**Comment by cdietrich** [comment]
java 9 should work in 2.13. are you sure you ran it with java 9? and do you have asm >= 6.0 installed?
