### ISSUE TITLE
[wizard] Tycho build is broken

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-core#704]
After creating a fresh MyDsl project with Eclipse plugin, Maven build and Language Server (regular) active, I get the following error

```
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT:compile (default) on project org.xtext.example.mydsl: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT:compile failed: Plugin org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.xtend:xtend-maven-plugin:jar:2.14.0-20180420.015623-171 -> org.eclipse.xtend:org.eclipse.xtend.core:jar:2.14.0-SNAPSHOT -> org.eclipse.jdt:org.eclipse.jdt.core:jar:3.13.100 -> org.eclipse.platform:org.eclipse.core.resources:jar:[3.12.0,4.0.0): No versions available for org.eclipse.platform:org.eclipse.core.resources:jar:[3.12.0,4.0.0) within specified range -> [Help 1]
```

This is strange since `org.eclipse.platform:org.eclipse.core.resources:3.12.0` is clearly available. Is this a temporary issue?

**Comment by cdietrich** [comment]
did you build with -U ?

**Comment by spoenemann** [comment]
With -U it's even worse:

```
[WARNING] Error injecting: org.eclipse.xtend.maven.XtendCompile
java.lang.NoClassDefFoundError: com/google/common/base/Predicate
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:658)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:882)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1006)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1038)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Predicate
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 55 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.xtext.example.mydsl.parent ..................... SUCCESS [  0.001 s]
[INFO] org.xtext.example.mydsl ............................ FAILURE [ 33.176 s]
[INFO] org.xtext.example.mydsl.ide ........................ SKIPPED
[INFO] org.xtext.example.mydsl.ui ......................... SKIPPED
[INFO] org.xtext.example.mydsl.target ..................... SKIPPED
[INFO] org.xtext.example.mydsl.tests ...................... SKIPPED
[INFO] org.xtext.example.mydsl.ui.tests ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.281 s
[INFO] Finished at: 2018-04-20T09:42:41+02:00
[INFO] Final Memory: 81M/756M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT:compile (default) on project org.xtext.example.mydsl: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT:compile failed: A required class was missing while executing org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT:compile: com/google/common/base/Predicate
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.xtend:xtend-maven-plugin:2.14.0-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtend/xtend-maven-plugin/2.14.0-SNAPSHOT/xtend-maven-plugin-2.14.0-SNAPSHOT.jar
[ERROR] urls[1] = file:/Users/spoenemann/.m2/repository/com/google/guava/guava/22.0-SNAPSHOT/guava-22.0-SNAPSHOT.jar
[ERROR] urls[2] = file:/Users/spoenemann/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[3] = file:/Users/spoenemann/.m2/repository/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar
[ERROR] urls[4] = file:/Users/spoenemann/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
[ERROR] urls[5] = file:/Users/spoenemann/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
[ERROR] urls[6] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtend/org.eclipse.xtend.core/2.14.0-SNAPSHOT/org.eclipse.xtend.core-2.14.0-SNAPSHOT.jar
[ERROR] urls[7] = file:/Users/spoenemann/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.core/3.13.100/org.eclipse.jdt.core-3.13.100.jar
[ERROR] urls[8] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.resources/3.12.0/org.eclipse.core.resources-3.12.0.jar
[ERROR] urls[9] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.expressions/3.6.0/org.eclipse.core.expressions-3.6.0.jar
[ERROR] urls[10] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.runtime/3.13.0/org.eclipse.core.runtime-3.13.0.jar
[ERROR] urls[11] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.jobs/3.9.3/org.eclipse.core.jobs-3.9.3.jar
[ERROR] urls[12] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.equinox.registry/3.7.0/org.eclipse.equinox.registry-3.7.0.jar
[ERROR] urls[13] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.equinox.preferences/3.7.0/org.eclipse.equinox.preferences-3.7.0.jar
[ERROR] urls[14] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.contenttype/3.6.0/org.eclipse.core.contenttype-3.6.0.jar
[ERROR] urls[15] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.equinox.app/1.3.400/org.eclipse.equinox.app-1.3.400.jar
[ERROR] urls[16] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.filesystem/1.7.0/org.eclipse.core.filesystem-1.7.0.jar
[ERROR] urls[17] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.text/3.6.100/org.eclipse.text-3.6.100.jar
[ERROR] urls[18] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.core.commands/3.9.0/org.eclipse.core.commands-3.9.0.jar
[ERROR] urls[19] = file:/Users/spoenemann/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.compiler.apt/1.3.60/org.eclipse.jdt.compiler.apt-1.3.60.jar
[ERROR] urls[20] = file:/Users/spoenemann/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.compiler.tool/1.2.51/org.eclipse.jdt.compiler.tool-1.2.51.jar
[ERROR] urls[21] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.xbase/2.14.0-SNAPSHOT/org.eclipse.xtext.xbase-2.14.0-SNAPSHOT.jar
[ERROR] urls[22] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.common.types/2.14.0-SNAPSHOT/org.eclipse.xtext.common.types-2.14.0-SNAPSHOT.jar
[ERROR] urls[23] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.14.0-SNAPSHOT/org.eclipse.xtext.xbase.lib-2.14.0-SNAPSHOT.jar
[ERROR] urls[24] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.util/2.14.0-SNAPSHOT/org.eclipse.xtext.util-2.14.0-SNAPSHOT.jar
[ERROR] urls[25] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.smap/2.14.0-SNAPSHOT/org.eclipse.xtext.smap-2.14.0-SNAPSHOT.jar
[ERROR] urls[26] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtext/org.eclipse.xtext/2.14.0-SNAPSHOT/org.eclipse.xtext-2.14.0-SNAPSHOT.jar
[ERROR] urls[27] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.8.0/org.eclipse.equinox.common-3.8.0.jar
[ERROR] urls[28] = file:/Users/spoenemann/.m2/repository/org/eclipse/platform/org.eclipse.osgi/3.11.2/org.eclipse.osgi-3.11.2.jar
[ERROR] urls[29] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtend/org.eclipse.xtend.lib/2.14.0-SNAPSHOT/org.eclipse.xtend.lib-2.14.0-SNAPSHOT.jar
[ERROR] urls[30] = file:/Users/spoenemann/.m2/repository/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.14.0-SNAPSHOT/org.eclipse.xtend.lib.macro-2.14.0-SNAPSHOT.jar
[ERROR] urls[31] = file:/Users/spoenemann/.m2/repository/org/eclipse/emf/org.eclipse.emf.common/2.12.0/org.eclipse.emf.common-2.12.0.jar
[ERROR] urls[32] = file:/Users/spoenemann/.m2/repository/org/eclipse/emf/org.eclipse.emf.ecore/2.12.0/org.eclipse.emf.ecore-2.12.0.jar
[ERROR] urls[33] = file:/Users/spoenemann/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar
[ERROR] urls[34] = file:/Users/spoenemann/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[35] = file:/Users/spoenemann/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar
[ERROR] urls[36] = file:/Users/spoenemann/.m2/repository/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.jar
[ERROR] urls[37] = file:/Users/spoenemann/.m2/repository/org/ow2/asm/asm-tree/6.0/asm-tree-6.0.jar
[ERROR] urls[38] = file:/Users/spoenemann/.m2/repository/org/ow2/asm/asm/6.0/asm-6.0.jar
[ERROR] urls[39] = file:/Users/spoenemann/.m2/repository/org/eclipse/aether/aether-util/1.0.0.v20140518/aether-util-1.0.0.v20140518.jar
[ERROR] urls[40] = file:/Users/spoenemann/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[41] = file:/Users/spoenemann/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[42] = file:/Users/spoenemann/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0.M1/org.eclipse.sisu.inject-0.3.0.M1.jar
[ERROR] urls[43] = file:/Users/spoenemann/.m2/repository/org/sonatype/sisu/sisu-guice/3.2.3/sisu-guice-3.2.3-no_aop.jar
[ERROR] urls[44] = file:/Users/spoenemann/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[45] = file:/Users/spoenemann/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[46] = file:/Users/spoenemann/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[47] = file:/Users/spoenemann/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[48] = file:/Users/spoenemann/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[49] = file:/Users/spoenemann/.m2/repository/org/eclipse/emf/org.eclipse.emf.ecore.xmi/2.12.0/org.eclipse.emf.ecore.xmi-2.12.0.jar
[ERROR] urls[50] = file:/Users/spoenemann/.m2/repository/org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar
[ERROR] urls[51] = file:/Users/spoenemann/.m2/repository/org/eclipse/emf/org.eclipse.emf.codegen/2.11.0-v20150806-0404/org.eclipse.emf.codegen-2.11.0-v20150806-0404.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.xtext.example.mydsl:org.xtext.example.mydsl.parent:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.google.common.base.Predicate
```

**Comment by cdietrich** [comment]
which java version?

**Comment by spoenemann** [comment]
I've set the command line to Java 8, but I also have Java 9 installed. `mvn` should pick the one where `$JAVA_HOME` is pointing to, right? That's Java 8 in my case.

**Comment by cdietrich** [comment]
did you try that with a fresh build specific maven repo?

**Comment by spoenemann** [comment]
That actually helps. Seems like I need to clear my `~/.m2` 🙄
