### ISSUE TITLE
[LanguageServer] didClose can be a delete as well

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#73]
If i delete a file in VSCode the server gets a didClose event and then does a read on the file

```
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /Users/dietrich/Documents/workspaceNeon_langserv/org.example.domainmodel.parent/example/src/demo/xxx.dmodel (No such file or directory)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:81)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:58)
	at org.eclipse.xtext.build.Indexer.getDeltasForChangedResources(Indexer.java:312)
	at org.eclipse.xtext.build.Indexer.computeAndIndexAffected(Indexer.java:235)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:199)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:430)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:411)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:117)
	at org.eclipse.xtext.ide.server.BuildManager.internalBuild(BuildManager.java:172)
	at org.eclipse.xtext.ide.server.BuildManager.doBuild(BuildManager.java:125)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doBuild(WorkspaceManager.java:141)
	at org.eclipse.xtext.ide.server.WorkspaceManager.didClose(WorkspaceManager.java:190)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$didClose$8(LanguageServerImpl.java:309)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runWrite$1(RequestManager.java:93)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 3 more
Caused by: java.io.FileNotFoundException: /Users/dietrich/Documents/workspaceNeon_langserv/org.example.domainmodel.parent/example/src/demo/xxx.dmodel (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
```

i assume we should be failsafe when reading the file and when it does not exist asume a delte on the file

**Comment by cdietrich** [comment]
fixed by

https://github.com/eclipse/xtext-core/commit/aea7ec628c78e32cde5c7e991c2559417136f071
