### ISSUE TITLE
Parsing in reconciler failed issue when feature is not assigned

### ISSUE THREAD

**Issue by karypid** [eclipse/xtext-core#773]
From [this forum thread](https://www.eclipse.org/forums/index.php/t/1093873/):

When the entry rule references another rule without assignment, unstable behaviour can occur. The parser will fail if the first expression is missing with exception:

```
4719 [Worker-6] ERROR org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy  - Parsing in reconciler failed.
java.lang.NullPointerException
	at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:263)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:182)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:90)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:450)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:430)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:364)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:433)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:166)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:361)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
To reproduce use grammar:

```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model: {Model}
    'greetings' '{'
    greetings+=Greeting*
    '}';

Greeting:
    SimpleGreeting | GoodMorning | GoodEvening | CompoundGreeting;

CompoundGreeting:
    'greet' name=ID '{' 
        lines+=CompoundGreetingMember*
    '}'
;

CompoundGreetingMember:
    RefGreeting | InlineGreeting
;

InlineGreeting:
    GoodMorning | GoodEvening
;

RefGreeting:
    'and' name=ID greet=[Greeting]
;

SimpleGreeting:
    'Hello' name=ID '!';

GoodMorning:
    'Good' 'morning' name=ID '!';

GoodEvening:
    'Good' 'evening' name=ID '!';
```

and create test file:

```
// day HappyDay

greetings {
	Hello X !
	Good morning Y !
	Good evening Z !
	
	greet script {
		Good morning A !
		Good evening B !
		and Thinking X
	}
}
```

Then modify grammar to require the commented-out top portion of the test file:

```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
    Day
    'greetings' '{'
    greetings+=Greeting*
    '}';

Day:
    'day' name=ID;

Greeting:
    SimpleGreeting | GoodMorning | GoodEvening | CompoundGreeting;

CompoundGreeting:
    'greet' name=ID '{' 
        lines+=CompoundGreetingMember*
    '}'
;

CompoundGreetingMember:
    RefGreeting | InlineGreeting
;

InlineGreeting:
    GoodMorning | GoodEvening
;

RefGreeting:
    'and' name=ID greet=[Greeting]
;

SimpleGreeting:
    'Hello' name=ID '!';

GoodMorning:
    'Good' 'morning' name=ID '!';

GoodEvening:
    'Good' 'evening' name=ID '!';
```

Additional exception/issue mentioned in forum thread seem to be cascading errors that stem from above.

**Comment by cdietrich** [comment]
@szarnekow is this a missing validation on the grammar and a error in the parser generation

(note that the first rulecall in the entry rule to `Day` is not assigned)

**Comment by ArneDeutsch** [comment]
I've stprit down the example a bit. The exact same exception can be reproduced with the following grammar:
```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	Day
    greeting=Greeting;

Day:
    'day' name=ID;

Greeting:
    'greeting' name=ID;
```

Use the following example file to test the grammar:
`greeting A`

**Comment by ArneDeutsch** [comment]
I would think that this is a missing validation indeed. The following rule creates an error marker "An unassigned rule call is not allowed, when the 'current' was already created.":
```
Model:
    greeting=Greeting
    Day;
```
Hence in my opinion the rule
```
Model:
    Day
    greeting=Greeting;
```
should create an error marker "An assignement is not allowed after an unassigned rule call." at the `greeting` token.

**Comment by szarnekow** [comment]
> should create an error marker "An assignement is not allowed after an unassigned rule call, when the 'current' was already created."

This is actually not true. Xtext.xtext contains this pattern: 
```
TerminalToken returns AbstractElement:
	TerminalTokenElement cardinality=('?'|'*'|'+')?
;
```

Subsequent assignments will simply manipulate the `current` instance which was returned by the unassigned rule call.

Not sure why this is not handled correctly on the root node.

**Comment by cdietrich** [comment]
see also https://bugs.eclipse.org/bugs/show_bug.cgi?id=508518
