### ISSUE TITLE
Bogus Validation in MaxLineWidthDocument

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#778]
```org.eclipse.xtext.formatting2.FormattingNotApplicableException
	at org.eclipse.xtext.formatting2.internal.MaxLineWidthDocument.validate(MaxLineWidthDocument.java:55)
	at org.eclipse.xtext.formatting2.internal.MaxLineWidthDocument.validate(MaxLineWidthDocument.java:60)
	at org.eclipse.xtext.formatting2.internal.MaxLineWidthDocument.addReplacer(MaxLineWidthDocument.java:32)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.set(FormattableDocument.java:321)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.append(FormattableDocument.java:87)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter.formatExpressionsMultiline(XbaseFormatter.java:1324)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter._format(XbaseFormatter.java:1147)
	at org.eclipse.xtend.core.formatting2.XtendFormatter.format(XtendFormatter.java:702)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.format(FormattableDocument.java:188)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter.lambda$19(XbaseFormatter.java:294)
	at org.eclipse.xtext.formatting2.internal.ConditionalReplacer.createReplacements(ConditionalReplacer.java:41)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:146)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.renderToTextReplacements(FormattableDocument.java:293)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.format(AbstractFormatter2.java:280)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter.exec(ContentFormatter.java:90)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter$FormattingUnitOfWork.exec(ContentFormatter.java:57)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter$FormattingUnitOfWork.exec(ContentFormatter.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.priorityReadOnly(XtextDocument.java:491)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.priorityReadOnly(XtextDocument.java:146)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter.format(ContentFormatter.java:103)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:1031)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1461)
	at org.eclipse.xtend.ide.editor.RichStringAwareSourceViewer.doOperation(RichStringAwareSourceViewer.java:260)
	at org.eclipse.ui.texteditor.TextOperationAction$1.run(TextOperationAction.java:130)
```

https://bugs.eclipse.org/bugs/show_bug.cgi?id=474468

> About the validation: Looks like the condition is plain wrong if (newLineMin != null && newLineMin > 0) should likely read if (newLineMin != null && newLineMin < 0)

**Comment by cdietrich** [comment]
Fixed in 2.15
