### ISSUE TITLE
Generate Testlanguages Fails

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#834]
./gradlew clean generateTestLanguages -PuseJenkinsSnapshots=true

```
24871 [main] INFO  text.xtext.generator.XtextGenerator  - Generating org.eclipse.xtext.testlanguages.fileAware.FileAwareTestLanguage
24871 [main] INFO  xt.generator.XtextGeneratorLanguage  - No explicit fileExtensions configured. Using '*.[fileawaretestlanguage]'.
25096 [main] INFO  nerator.ecore.EMFGeneratorFragment2  - Generating EMF model code
25099 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/testlanguage/FileAware' from 'platform:/resource/org.eclipse.xtext.testlanguages/model/generated/FileAwareTestLanguage.genmodel'
25814 [main] INFO  text.xtext.generator.XtextGenerator  - Generating common infrastructure
25826 [main] INFO  .emf.mwe2.runtime.workflow.Workflow  - Done.
:org.eclipse.xtext.tests:compileMwe2Java
:org.eclipse.xtext.tests:processMwe2Resources NO-SOURCE
:org.eclipse.xtext.tests:mwe2Classes
:org.eclipse.xtext.tests:processTestResources
:org.eclipse.xtext.tests:generateTestLanguages
1    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - [XtextLinkingDiagnostic: null:47 Couldn't resolve reference to JvmType 'testlanguages.ecore.EcoreSupport'.]
java.lang.IllegalStateException: [XtextLinkingDiagnostic: null:47 Couldn't resolve reference to JvmType 'testlanguages.ecore.EcoreSupport'.]
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:88)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
:org.eclipse.xtext.tests:generateTestLanguages FAILED
```

**Comment by cdietrich** [comment]
Fixed in 2.15
