### ISSUE TITLE
Bad Positions for Diagnostics at end of line when including newline

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#922]
from the spec

> If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.

sample model

```
...
Hello

```

currently sent message
```
{
  "jsonrpc": "2.0",
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///Users/dietrich/git/xtext-languageserver-example/demo/b.mydsl",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 12,
            "character": 5
          },
          "end": {
            "line": 12,
            "character": 7
          }
        },
        "severity": 1,
        "code": "org.eclipse.xtext.diagnostics.Diagnostic.Syntax",
        "message": "mismatched input \u0027\u003cEOF\u003e\u0027 expecting RULE_ID"
      }
    ]
  }
}
```

according to the spec:

```
{
    start: { line: 5, character: 23 },
    end : { line 6, character : 0 }
}
```

**Comment by cdietrich** [comment]
when using in [Intellij](https://github.com/gtache/intellij-lsp) this leads to

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 7
	at java.lang.String.substring(String.java:1963)
	at com.github.gtache.lsp.utils.DocumentUtils$.LSPPosToOffset(DocumentUtils.scala:73)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$diagnostics$5(EditorEventManager.scala:527)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945)
	at com.github.gtache.lsp.utils.ApplicationUtils$.computableReadAction(ApplicationUtils.scala:26)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$diagnostics$4(EditorEventManager.scala:527)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$diagnostics$4$adapted(EditorEventManager.scala:520)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at com.github.gtache.lsp.editor.EditorEventManager.$anonfun$diagnostics$1(EditorEventManager.scala:520)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Atom and VSCode survive the bogus notifications

**Comment by cdietrich** [comment]
@kittaakos how is this usecase treated in theia?

**Comment by cdietrich** [comment]
am not sure if something like this would be feasable

```
private def void publishDiagnostics(URI uri, Iterable<? extends Issue> issues) {
		initialized.thenAccept([
			val diagnostics = new PublishDiagnosticsParams => [
				it.uri = toUriString(uri)
				it.diagnostics = workspaceManager.doRead(uri) [document, resource|
					issues.filter[severity !== IGNORE].map[toDiagnostic(document, it)].toList
				]
			]
			client.publishDiagnostics(diagnostics)
		])
	}

	private def Diagnostic toDiagnostic(Document document, Issue issue) {
		new Diagnostic => [
			code = issue.code
			severity = switch issue.severity {
				case ERROR: DiagnosticSeverity.Error
				case WARNING: DiagnosticSeverity.Warning
				case INFO: DiagnosticSeverity.Information
				default: DiagnosticSeverity.Hint
			}
			message = issue.message
			val start = document.getPosition(issue.offset)
			val end = document.getPosition(issue.offset+issue.length)
            val lineNumber = (issue.lineNumber ?: 1) - 1
            val column = (issue.column ?: 1) - 1
            val length = (issue.length ?: 0)
			range = new Range(
				start,
				end
			)
		]
	}
```

**Comment by cdietrich** [comment]
@svenefftinge @kittaakos any thoughts?

**Comment by cdietrich** [comment]
WIP for a more sophisticated solution is here: https://github.com/eclipse/xtext-core/tree/cd_issue922_variant_b

**Comment by cdietrich** [comment]
first fix in now inplace. will leave open for further improvement

**Comment by mmews-n4** [comment]
Note the two citations from the LSP spec (one @cdietrich cited above already):

- **(1) Spec says, marking the last character of a line is done by referencing the start of the next line**
>If you want to specify a range that contains a line including the line ending character(s) 
>then use an end position denoting the start of the next line.

- **(2) Spec says, that LSP clients can deal with character positions greater than the line length**
```ts
interface Position {
	/**
	 * Line position in a document (zero-based).
	 */
	line: number;

	/**
	 * Character offset on a line in a document (zero-based). Assuming that the line is
	 * represented as a string, the `character` value represents the gap between the
	 * `character` and `character + 1`.
	 *
	 * If the character value is greater than the line length it defaults back to the
	 * line length.
	 */
	character: number;
}
```

My conclusions:
- Regarding the `StringIndexOutOfBoundsException` of IntelliJ: Spec (2) means IMHO, that the LSP client of IntelliJ does it wrong.

- Combing these specs means, that ranges that should include the last character of a line have to do it like (1). Otherwise, the last character would not be marked. However, as noted [here](https://github.com/eclipse/xtext-core/pull/1316#issuecomment-562123551), VSCode will actually also mark the last character without using (1) which means that VSCode is not strict about the LSP spec.

Hence I think that dealing with `StringIndexOutOfBoundsException` is not necessary.

**Comment by cdietrich** [comment]
Defaulting and have correct positions here are two things 

I wonder if your change makes mine superfluous/ possibly cleaned up

**Comment by mmews-n4** [comment]
Right, so defaulting solves `StringIndexOutOfBoundsException`.

Correct positions can be calculated. I prepared that already on my machine and can push it to branch issue_end_position. But that would make it necessary to introduce another variable (which I called `hasLineBreakAfterColumnEnd`. Would you either like to have correct position by introducing that additional variable, or would you instead have no additional variable but then have an incorrect(*) position in some LSP clients (not VSCode)? I think, that this is our choice. (The latter one is the PR (issue_end_position) and I prepared the former one already, as I mentioned).

(*) incorrect means that the last character of a line is never marked.

**Comment by mmews-n4** [comment]
To show some of the changes that would be necessary additionally, mind the code snipped below. Also note, that analogous to `getLineNumberEnd()` and `getColumnEnd()`, the additional method `hasLineBreakAfterColumnEnd ()` needs to be added.

**LanguageServerImpl**
```java
	protected Diagnostic toDiagnostic(Issue issue) {
		Diagnostic result = new Diagnostic();
		result.setCode(issue.getCode());
		result.setMessage(issue.getMessage());
		result.setSeverity(toDiagnosticSeverity(issue.getSeverity()));

		// last character is not included in LSP, hence proceed to next character and respect line breaks
		int endLine = issue.getLineNumberEnd() + (issue.hasLineBreakAfterColumnEnd()? 1 : 0);
		int endColumn = issue.hasLineBreakAfterColumnEnd()? 1 : issue.getColumnEnd();

		// line and column numbers in LSP are 0-based
		Position start = new Position(issue.getLineNumber() - 1, issue.getColumn() - 1);
		Position end = new Position(endLine - 1, endColumn - 1);
		result.setRange(new Range(start, end));
		return result;
	}
```

**Comment by cdietrich** [comment]
move to 2.22
